[package]
name = "ankamantatra-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
russenger = { version = "0.1.6", git = "https://github.com/j03-dev/russenger", branch = "nightly" }
actix-web = "4"
serde_json = "1.0.117"
serde = { version = "1.0.202", features = ["derive"] }
rand = "0.8.5"
