[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ankamantatra"
version = "0.1.0"
description = ""
readme = "README.md"
authors = [
    {
        name = "",
        email = "gtsierenana@gmail.com",
    },
    {
        name = "",
        email = "",
    }
]
license = { file = "LICENSE" }
dependecies = [

]