[package]
name = "migrate"
version = "0.1.0"
edition = "2021"

[dependencies.models]
path = "../models"

[dependencies]
rusql-alchemy = { version = "*", git = "https://github.com/j03-dev/rusql-alchemy", branch = "main" }
tokio = { version = "^1.38.0", features = ["full"] }
